### ISSUE TITLE
Explicit CKAN and DKAN support

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackage-from-remote-js#11]
# Description

We now have two remote types: CKAN and DKAN. We also have a single version declared for each type. We want to be explicit about API version support (even if different versions return the same response).
# Tasks
- [x] For both CKAN and DKAN, explicitly support each API version in the config objects (1, 2, 3 for each AFAIK)
- [x] always have an explicit version called "latest", which is the default of no version is passed, and which, for each CKAN and DKAN right now, is mapped to 3.0
- [x] Go over the various notes here https://github.com/okfn/datapackagist/issues/165 from @richhall and ensure we have covered DKAN correctly
- [x] Tests for each API version, for each remote
